# (initramfs) mkdir -p /x
# (initramfs) FUSE_LIBRARY_PATH=/lib/x86_64-linux-gnu/libfuse.so.2 mount.fuse.http2  http://10.128.2.4/ /x
# WARNING:root:Server does not support HTTP/2? (http://10.128.2.4/)
# fuse: device not found, try 'modprobe fuse' first
# Traceback (most recent call last):
#   File "/sbin/mount.fuse.http2", line 203, in <module>
#     main()
#   File "/sbin/mount.fuse.http2", line 62, in main
#     return fuse.FUSE(HTTP2FS(args.url),
#   File "/usr/lib/python3/dist-packages/fusepy.py", line 711, in __init__
#     raise RuntimeError(err)
# RuntimeError: 1
# (initramfs) modprobe fuse
# (initramfs) FUSE_LIBRARY_PATH=/lib/x86_64-linux-gnu/libfuse.so.2 mount.fuse.http2  http://10.128.2.4/ /x
# WARNING:root:Server does not support HTTP/2? (http://10.128.2.4/)
# fuse: device not found, try 'modprobe fuse' first
# Traceback (most recent call last):
#   File "/sbin/mount.fuse.http2", line 203, in <module>
#     main()
#   File "/sbin/mount.fuse.http2", line 62, in main
#     return fuse.FUSE(HTTP2FS(args.url),
#   File "/usr/lib/python3/dist-packages/fusepy.py", line 711, in __init__
#     raise RuntimeError(err)
# RuntimeError: 1
fuse
